### PR TITLE
Added a scenario tutorial and a basic http scenario example.

### PR DESCRIPTION
**Pull request by moigagoo**

### CODE REVIEW

**Comment by parsifal-47** [comment]
CI failed because of example validation,
I suggest to move examples/localhost.erl to this http worker examples because it is not built-in

**Comment by moigagoo** [comment]
Is it possible to make http worker built in instead? AFAIU http worker is one of the most commonly used workers. By any measure, it's more useful than dummy worker, which is built in.

I don't like the idea of burying the example deeper in the file tree because it would be harder to find there, and _examples_ is the most obvious place to look for it.

**Comment by parsifal-47** [comment]
Right now it could be a problem to add http workers to default build because some people probably have already cloned them and made some adjustments.

I suggest to keep http workers separate and in near future make more practical worker instead of dummy and rewrite all the examples with this worker.

So please move examples to http folder and we'll try to make the improvement I mentioned asap

**Comment by moigagoo** [comment]
In localhost.erl, it's explicitly declared to install the http worker before running the scenario, so there's no need to move it to workers/http/examples.

**Pull request merged**
