### PR TITLE
add erlang 20 for test

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by benoitc** [comment]
bump

**Comment by deadtrickster** [comment]
Dialyzer failed I guess

**Comment by parsifal-47** [comment]
oh, thanks for "bumping"!
we forgot about this PR, will follow-up in few days

**Comment by getong** [comment]
It works. Do I need to squash it?

**Comment by parsifal-47** [comment]
no need to squash, thanks a lot for your contribution!

**Comment by parsifal-47** [comment]
there is no need to squash, thanks a lot for your contribution!
should be merged already, some interface glitch

**Pull request merged**
