### PR TITLE
Minor doc correction . Let users who fork run on their forked branches 

### PR DESCRIPTION
**Pull request by linearregression**
* correct path to doc on readme & minor clarification
* add 18.1 for travis
* mzbench_api.app.src.script:  let user who forked run against their repo
* add more editor buffers files to gitignore

### CODE REVIEW

**Comment by linearregression** [comment]
Hi,I have not changed the source code. Do you know why the basic acceptance tests are unstable under travisci runs?  They will pass on one otp release but fail on others and are not consistent across travisCI runs. 
Thanks

**Comment by merlin86** [comment]
Hello!

The acceptance tests are unstable under TravisCI runs because of the race condition in the server - benchmarking nodes communication. If the benchmark itself is very short (as is the case in the tests) it finishes before the first bunch of metrics data was transmitted (they are generated every 10 seconds). At the benchmark end, the director node forces the metrics transmission, then terminates instantly. The server sees that the benchmark director node has finished its execution and begins the clean up of the nodes. Sometimes they are wiped out before the metric transmission has finished. It causes the failure of the "data endpoint" test.

Unfortunately, this race condition is difficult to fix properly because of the exometer limitation (it has no method to wait that all the metrics was reported). But I have created a temporary fix in our private repository by adding a short sleep at the end of the benchmark. It should by committed in the public repo shortly.

We are in the middle of the complete rewrite of the metrics storage and getting rid of the exometer by the way. It should fix this bug for good.

I hope it helped!

PS: Our company policy is that all contributors must sign the CLA. So we can't merge your pull request until you do so. Sorry!

**Comment by linearregression** [comment]
Ok. So what other reasons to prompt you rewrite of metrics storage and replacing exometer? I tried signig the CLA. few times. It showed me 
Thank you
for signing the CLA!
we are now taking you back to GitHub

But nothing happened. I never set my git user and email using this account until these few days. Anu other venue for me to comply?

**Comment by parsifal-47** [comment]
Hello!
About CLA signup process: looks like your branch have commits from "root" and "edwardt", probably from "root@localhost" or something, you need to have these emails associated with your github account in order to signup this agreement. I recommend you to re-write committer email address to your github-registred email and pass signup process

**Pull request closed without merging**
